name: Convert BanAD.list to JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch BanAD.list
      run: |
        # 下载 BanAD.list 文件
        curl -s https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list -o BanAD.list

    - name: Convert to JSON
      run: |
        # 初始化 JSON 文件
        echo '{
          "rules": [
            {
              "domain_keyword": [],
              "domain_suffix": []
            }
          ]
        }' > aa.json

        # 遍历 BanAD.list 并填充 JSON
        while IFS=, read -r type value; do
          # 去掉空行和注释行
          if [[ -z "$type" || "$type" == \#* ]]; then
            continue
          fi

          if [[ "$type" == "DOMAIN-KEYWORD" ]]; then
            # 处理 DOMAIN-KEYWORD 类型
            jq --arg value "$value" '.rules[0].domain_keyword += [$value]' aa.json > tmp.json && mv tmp.json aa.json
          elif [[ "$type" == "DOMAIN-SUFFIX" ]]; then
            # 处理 DOMAIN-SUFFIX 类型
            jq --arg value "$value" '.rules[0].domain_suffix += [$value]' aa.json > tmp.json && mv tmp.json aa.json
          fi
        done < BanAD.list

    - name: Move JSON to Target Directory
      run: |
        # 创建目标目录并移动文件
        mkdir -p singbox/rule/
        mv aa.json singbox/rule/aa.json

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add singbox/rule/aa.json
        git commit -m "Update aa.json with converted rules" || echo "No changes to commit"
        git push
