name: Convert BanAD.list and BanProgramAD.list to JSON

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日执行一次
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch BanAD.list and BanProgramAD.list
      run: |
        # 下载 BanAD.list 和 BanProgramAD.list 文件
        curl -s https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list -o BanAD.list
        curl -s https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list -o BanProgramAD.list

    - name: Convert BanAD.list to JSON
      run: |
        # 初始化 BanAD.json 文件
        echo '{
          "rules": [
            {
              "domain_keyword": [],
              "domain_suffix": [],
              "domain": [],
              "ip_cidr": []
            }
          ]
        }' > BanAD.json

        # 遍历 BanAD.list 并填充 JSON
        while IFS=, read -r type value extra; do
          # 去掉空行和注释行
          if [[ -z "$type" || "$type" == \#* ]]; then
            continue
          fi

          if [[ "$type" == "DOMAIN-KEYWORD" ]]; then
            jq --arg value "$value" '.rules[0].domain_keyword += [$value]' BanAD.json > tmp.json && mv tmp.json BanAD.json
          elif [[ "$type" == "DOMAIN-SUFFIX" ]]; then
            jq --arg value "$value" '.rules[0].domain_suffix += [$value]' BanAD.json > tmp.json && mv tmp.json BanAD.json
          elif [[ "$type" == "DOMAIN" ]]; then
            jq --arg value "$value" '.rules[0].domain += [$value]' BanAD.json > tmp.json && mv tmp.json BanAD.json
          elif [[ "$type" == "IP-CIDR" ]]; then
            jq --arg value "$value" '.rules[0].ip_cidr += [$value]' BanAD.json > tmp.json && mv tmp.json BanAD.json
          fi
        done < BanAD.list

    - name: Convert BanProgramAD.list to JSON
      run: |
        # 初始化 BanProgramAD.json 文件
        echo '{
          "rules": [
            {
              "domain_keyword": [],
              "domain_suffix": [],
              "domain": [],
              "ip_cidr": []
            }
          ]
        }' > BanProgramAD.json

        # 遍历 BanProgramAD.list 并填充 JSON
        while IFS=, read -r type value extra; do
          # 去掉空行和注释行
          if [[ -z "$type" || "$type" == \#* ]]; then
            continue
          fi

          if [[ "$type" == "DOMAIN-KEYWORD" ]]; then
            jq --arg value "$value" '.rules[0].domain_keyword += [$value]' BanProgramAD.json > tmp.json && mv tmp.json BanProgramAD.json
          elif [[ "$type" == "DOMAIN-SUFFIX" ]]; then
            jq --arg value "$value" '.rules[0].domain_suffix += [$value]' BanProgramAD.json > tmp.json && mv tmp.json BanProgramAD.json
          elif [[ "$type" == "DOMAIN" ]]; then
            jq --arg value "$value" '.rules[0].domain += [$value]' BanProgramAD.json > tmp.json && mv tmp.json BanProgramAD.json
          elif [[ "$type" == "IP-CIDR" ]]; then
            jq --arg value "$value" '.rules[0].ip_cidr += [$value]' BanProgramAD.json > tmp.json && mv tmp.json BanProgramAD.json
          fi
        done < BanProgramAD.list

    - name: Move JSON to Target Directory
      run: |
        # 创建目标目录并移动文件
        mkdir -p singbox/rule/
        mv BanAD.json singbox/rule/BanAD.json
        mv BanProgramAD.json singbox/rule/BanProgramAD.json

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add singbox/rule/BanAD.json singbox/rule/BanProgramAD.json
        git commit -m "Update BanAD.json and BanProgramAD.json with converted rules" || echo "No changes to commit"
        git push
